### ISSUE TITLE
Building and running user programs

### ISSUE THREAD

**Issue by samrat** [real-xinu/xinu-bbb#2]
Chapter 2 of the book provides several example programs, all of which seem to be user-level programs with a separate `main`. In the book or in the code, I couldn't find any documentation/examples on how to run such a program.

Could you provide an example of how to do this?

**Comment by samrat** [comment]
I ended up "converting" the example programs into shell commands(ie. as xsh_* functions). Is there a better way to do this?

**Comment by douglascomer** [comment]
> I ended up "converting" the example programs into shell commands(ie. as xsh_* functions). Is there a better way to go about this?
> 

The examples are just to give the reader some idea about how to get started.  It’s great that you converted them to shell commands.  Now you’re ready to tackle something more substantial. :-)

Douglas Comer

**Comment by samrat** [comment]
Thanks :)
